#!/usr/bin/env python3
"""Regenerate results/summary.md, results/summary_runs.csv and
results/windows.csv from results/raw. Standard library only.

Steady-state label: the measurement phase is split into halves by window;
if mean WA of the two halves differs by less than 2% for every seed, the
configuration is labelled "steady", otherwise "transient".

Analytic reference: FIFO cleaning under uniform random single-stream writes
(the model in Hu et al. 2009 / Desnoyers 2012). With alpha = physical pages /
logical pages, the valid fraction u of a victim block solves
u = exp(-alpha * (1 - u)) and WA = 1 / (1 - u). It assumes one write stream
(GC relocations mixed with host writes), uniform random overwrites, and
pages per block large enough that a block's valid count is close to its
expectation; it is compared only against the single-frontier FIFO runs.
"""
import csv
import glob
import json
import math
import os
import statistics
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW = os.path.join(ROOT, "results", "raw")
OUT = os.path.join(ROOT, "results")


def fifo_model_wa(alpha):
    lo, hi = 0.0, 1.0 - 1e-12
    f = lambda u: u - math.exp(-alpha * (1.0 - u))
    # f(0) < 0 and f(1 - eps) > 0 for alpha > 1: bisect the non-trivial root.
    for _ in range(200):
        mid = (lo + hi) / 2
        if f(mid) < 0:
            lo = mid
        else:
            hi = mid
    u = (lo + hi) / 2
    return 1.0 / (1.0 - u), u


def load(exp):
    out = []
    for p in sorted(glob.glob(os.path.join(RAW, exp, "*.json"))):
        with open(p) as f:
            d = json.load(f)
        d["_file"] = os.path.relpath(p, ROOT)
        out.append(d)
    return out


def halves_drift(d):
    w = [x["wa"] for x in d["windows"] if x["measured"]]
    if len(w) < 4:
        return float("nan")
    a, b = w[: len(w) // 2], w[len(w) // 2:]
    ma, mb = statistics.mean(a), statistics.mean(b)
    return abs(mb - ma) / ma


def med_rng(vals, fmt="{:.3f}"):
    m = statistics.median(vals)
    if len(vals) == 1:
        return fmt.format(m)
    return f"{fmt.format(m)} [{fmt.format(min(vals))}-{fmt.format(max(vals))}]"


def table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def main():
    env = {}
    if os.path.exists(os.path.join(RAW, "environment.json")):
        with open(os.path.join(RAW, "environment.json")) as f:
            env = json.load(f)
    main_runs, model_runs, long_runs = load("main"), load("model"), load("long")
    all_runs = main_runs + model_runs + long_runs
    md = ["# FTL simulator results (generated by bench/summarize.py)", ""]
    if env:
        md += [f"- host: {env.get('host')} / {env.get('cpu')}, compiler: {env.get('compiler')}",
               f"- code revision `{env.get('git_rev')}`{' (dirty)' if env.get('git_dirty') else ''}, "
               f"collected {env.get('date_utc')}", ""]
    if all_runs:
        c = all_runs[0]["config"]
        cap = all_runs[0]["capacity"]
        md += [f"Geometry: {c['blocks']} blocks x {c['pages_per_block']} pages x "
               f"{c['page_size']} B ({cap['physical_pages'] * c['page_size'] >> 20} MiB physical). "
               f"All {len(all_runs)} runs verified every logical page after the run: "
               f"{all(r['verify']['ok'] for r in all_runs)}.", ""]

    # ---- main comparison ----
    groups = defaultdict(list)
    for r in main_runs:
        c = r["config"]
        groups[(c["workload"], c["spare_blocks"], c["policy"])].append(r)
    traces = defaultdict(set)
    for r in main_runs:
        c = r["config"]
        traces[(c["workload"], c["spare_blocks"], c["seed"])].add(r["trace_hash"])
    identical = all(len(v) == 1 for v in traces.values())
    if groups:
        md += ["## Greedy vs FIFO (dual write frontier)", "",
               "Precondition: one sequential fill of the logical space. Warm-up: 4x logical "
               "capacity of workload writes. Measurement: the next 8x logical capacity. "
               "Cells: median [min-max] over seeds.",
               f"Greedy and FIFO received identical traces for every (workload, spare, seed): "
               f"{identical}.", ""]
        rows = []
        order = {"seq": 0, "uniform": 1, "hotcold": 2}
        for key in sorted(groups, key=lambda k: (order[k[0]], k[1], k[2])):
            rs = groups[key]
            wl, spare, pol = key
            cap = rs[0]["capacity"]
            drift = max(halves_drift(r) for r in rs)
            rows.append([wl, f"{spare} ({cap['op_pct_of_logical']:.1f}%)", pol, len(rs),
                         med_rng([r["measure"]["write_amplification"] for r in rs]),
                         med_rng([r["measure"]["gc_pages_moved"] / r["measure"]["host_writes"]
                                  for r in rs]),
                         med_rng([1000 * r["measure"]["erases"] / r["measure"]["host_writes"]
                                  for r in rs], "{:.2f}"),
                         med_rng([r["erase_count"]["max_over_mean"] for r in rs], "{:.2f}"),
                         med_rng([r["erase_count"]["stddev"] for r in rs], "{:.1f}"),
                         "steady" if drift < 0.02 else f"transient ({100 * drift:.1f}%)"])
        md += [table(["workload", "spare blocks (OP)", "policy", "seeds", "WA",
                      "GC pages moved / host write", "blocks erased / 1k writes",
                      "erase max/mean", "erase stddev", "state (max half-to-half drift)"],
                     rows), ""]
        md += ["Erase counts are lifetime totals per block (all phases). WA = NAND page "
               "programs (host + GC) / host page writes, measured over the measurement "
               "phase only. GC is foreground and runs once per host block opened in steady "
               "state (1000/64 = 15.6 episodes per 1k writes in every configuration), so GC "
               "frequency is reported as blocks erased per 1k host writes.", ""]

        r0 = main_runs[0]
        m = r0["mapping_memory"]
        md += ["## Mapping-table memory (modelled controller DRAM)", "",
               table(["spare", "L2P bytes", "valid bitmap bytes", "per-block metadata bytes",
                      "total", "% of logical capacity"],
                     [[r["config"]["spare_blocks"], r["mapping_memory"]["l2p_bytes"],
                       r["mapping_memory"]["valid_bitmap_bytes"],
                       r["mapping_memory"]["block_meta_bytes"], r["mapping_memory"]["total_bytes"],
                       f"{r['mapping_memory']['pct_of_logical_capacity']:.3f}%"]
                      for r in {x["config"]["spare_blocks"]: x for x in main_runs}.values()]),
               "", "A 4-byte entry per 4 KiB logical page dominates (the usual ~0.1% "
               "DRAM-to-capacity ratio of page-mapped FTLs).", ""]

        md += ["## Simulator execution time and simulated device time", "",
               "Simulator speed is host CPU time for this C program. It is **not** SSD "
               "performance. Simulated device time uses the stated tR/tPROG/tBERS "
               "assumptions (single die, no parallelism) and is **simulated**, not measured.", ""]
        rows = []
        for key in sorted(groups, key=lambda k: (order[k[0]], k[1], k[2])):
            rs = groups[key]
            rows.append([key[0], key[1], key[2],
                         med_rng([r["simulator"]["host_writes_per_s"] / 1e3 for r in rs], "{:.0f}"),
                         med_rng([r["simulated_device"]["mean_us_per_host_write"] for r in rs],
                                 "{:.0f}")])
        md += [table(["workload", "spare", "policy", "simulator k host writes/s (host CPU)",
                      "simulated device us per host write"], rows),
               "", f"Timing assumptions: {main_runs[0]['simulated_device']['assumptions']}.", ""]

    # ---- analytic model check ----
    mg = defaultdict(list)
    for r in model_runs:
        c = r["config"]
        mg[(c["spare_blocks"], c["policy"])].append(r)
    if mg:
        md += ["## Sanity check against the analytic FIFO model (single write frontier)", "",
               "Model: u = exp(-alpha (1 - u)), WA = 1/(1 - u), alpha = physical/logical pages. "
               "Assumptions: uniform random overwrites, one write stream, FIFO cleaning. "
               "Only the single-frontier FIFO column matches all assumptions; greedy and the "
               "dual-frontier main runs are shown for context. In steady state this FTL always "
               "keeps one erased block in reserve (it holds no data and is outside the write "
               "cycle), so the corrected column uses alpha' = (blocks - 1) / logical blocks.", ""]
        rows = []
        for spare in sorted({k[0] for k in mg}):
            rs_f = mg.get((spare, "fifo"), [])
            rs_g = mg.get((spare, "greedy"), [])
            ref = (rs_f or rs_g)[0]
            alpha = ref["capacity"]["physical_pages"] / ref["capacity"]["logical_pages"]
            wa_model, u = fifo_model_wa(alpha)
            nb = ref["config"]["blocks"]
            wa_model1, _ = fifo_model_wa((nb - 1) / (nb - spare))
            fifo = statistics.median(r["measure"]["write_amplification"] for r in rs_f)
            dual = {p: [r["measure"]["write_amplification"] for r in groups.get(("uniform", spare, p), [])]
                    for p in ("fifo", "greedy")}
            rows.append([spare, f"{ref['capacity']['op_pct_of_logical']:.1f}%", f"{alpha:.4f}",
                         f"{wa_model:.3f}", f"{wa_model1:.3f}", f"{fifo:.3f}",
                         f"{100 * (fifo - wa_model) / wa_model:+.1f}%",
                         f"{100 * (fifo - wa_model1) / wa_model1:+.1f}%",
                         f"{statistics.median(r['measure']['write_amplification'] for r in rs_g):.3f}",
                         f"{statistics.median(dual['fifo']):.3f}" if dual["fifo"] else "-",
                         f"{statistics.median(dual['greedy']):.3f}" if dual["greedy"] else "-"])
        md += [table(["spare", "OP", "alpha", "FIFO model WA", "model, 1 block excluded",
                      "FIFO single-frontier WA", "vs model", "vs model (1 block excluded)", "greedy single-frontier WA", "FIFO dual WA",
                      "greedy dual WA"], rows), ""]

    # ---- long runs ----
    if long_runs:
        md += ["## Long runs: WA by window (uniform/hotcold, spare 72, seed 1, 40x logical "
               "capacity, no separate warm-up)", ""]
        rows = []
        marks = [2, 4, 8, 12, 20, 30, 40]
        for r in long_runs:
            c = r["config"]
            L = r["capacity"]["logical_pages"]
            byx = {round(w["end_writes"] / L, 1): w["wa"] for w in r["windows"]}
            rows.append([c["workload"], c["policy"]] +
                        [f"{byx.get(float(x), float('nan')):.3f}" for x in marks])
        md += [table(["workload", "policy"] + [f"window ending {x}x" for x in marks], rows), ""]

    with open(os.path.join(OUT, "summary.md"), "w") as f:
        f.write("\n".join(md))
    with open(os.path.join(OUT, "summary_runs.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["file", "workload", "spare_blocks", "policy", "single_frontier", "seed",
                    "wa", "gc_pages_moved", "host_writes", "gc_invocations", "erases",
                    "erase_min", "erase_max", "erase_mean", "erase_stddev", "trace_hash",
                    "verify_ok", "sim_host_writes_per_s", "halves_drift"])
        for r in all_runs:
            c = r["config"]
            w.writerow([r["_file"], c["workload"], c["spare_blocks"], c["policy"],
                        c["single_frontier"], c["seed"], r["measure"]["write_amplification"],
                        r["measure"]["gc_pages_moved"], r["measure"]["host_writes"],
                        r["measure"]["gc_invocations"], r["measure"]["erases"],
                        r["erase_count"]["min"], r["erase_count"]["max"],
                        r["erase_count"]["mean"], r["erase_count"]["stddev"], r["trace_hash"],
                        r["verify"]["ok"], r["simulator"]["host_writes_per_s"],
                        f"{halves_drift(r):.5f}"])
    with open(os.path.join(OUT, "windows.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["file", "workload", "spare_blocks", "policy", "single_frontier", "seed",
                    "end_writes", "end_x_logical", "measured", "wa", "moved", "erases"])
        for r in all_runs:
            c = r["config"]
            L = r["capacity"]["logical_pages"]
            for x in r["windows"]:
                w.writerow([r["_file"], c["workload"], c["spare_blocks"], c["policy"],
                            c["single_frontier"], c["seed"], x["end_writes"],
                            f"{x['end_writes'] / L:.3f}", x["measured"], x["wa"], x["moved"],
                            x["erases"]])
    print(f"wrote results/summary.md, summary_runs.csv, windows.csv ({len(all_runs)} runs)")


if __name__ == "__main__":
    main()
